### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es.array.filter'

### ISSUE THREAD

**Issue by JasonBoy** [ant-design/codemod-v4#93]
nodejs v10.16, 运行codemod很多core-js的错
```
Transform v3-Icon-to-v4-Icon
Processing 71 files...
Spawning 2 workers...
Sending 36 files to free worker...
Sending 35 files to free worker...
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es.array.filter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jason/.config/yarn/global/node_modules/@ant-design/codemod-v4/transforms/v3-Icon-to-v4-Icon.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/jason/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/jason/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
internal/modules/cjs/loader.js:638
    throw err;

.....

Error: Cannot find module 'core-js/modules/es.symbol'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jason/.config/yarn/global/node_modules/@ant-design/codemod-v4/transforms/v3-typings-to-compatible.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/jason/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/jason/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.475seconds
----------- antd4 dependencies alert -----------

It's recommended to install or upgrade these dependencies to ensure working well with antd4

> package.json file:  /Users/xxx/package.json

* Update antd^4.0.0 in dependencies
* Update @ant-design/icons^4.0.0 in dependencies
* Update @ant-design/compatible^1.0.0 in dependencies

----------- Thanks for using @ant-design/codemod 1.0.1 -----------
```

**Comment by vagusX** [comment]
you can try `@ant-design/codemod-v4@1.0.2`

**Comment by JasonBoy** [comment]
manually migrated 🤓

**Comment by nnecec** [comment]
> you can try `@ant-design/codemod-v4@1.0.2` @JasonBoy

still have this problem.

**Comment by nnecec** [comment]
codemod cli 会读我自己项目中的 babel 配置，把 babel config 删了就跑起来了。
